Table data_values {
  indicator_id int [ref: > indicators.id] // Relationship to indicators table
  country_id int [ref: > countries.id]    // Relationship to countries table
  unit_id int [ref: > units.id]           // Relationship to units table
  value_name_id int [ref: > value_names.id] // Relationship to value_names table
  jmp_category_id int [ref: > jmp_categories.id] // Relationship to jmp_categories table
  commitment_id int [ref: > commitments.id] // Relationship to commitments table
  year int
  value decimal
}

Table indicators {
  id int [pk]
  name varchar
}

Table countries {
  id int [pk]
  name varchar
}

Table units {
  id int [pk]
  name varchar
}

Table value_names {
  id int [pk]
  name varchar
}

Table jmp_categories {
  id int [pk]
  name varchar
}

Table commitments {
  id int [pk]
  name varchar
}
